### ISSUE TITLE
Pytest finds 0 items.

### ISSUE THREAD

**Issue by sganesh1975** [rajeshkumar426/Inventory-management#2]
![image](https://user-images.githubusercontent.com/700203/82511878-0b352d00-9ad4-11ea-93c7-83b008ba2536.png)

**Comment by rajeshkumar426** [comment]
Resolved. Changed file name testf.py to test_inventory.py because pytest looks for test_*.py files.
![unittest](https://user-images.githubusercontent.com/58596933/82532012-12088200-9b5e-11ea-9127-22f27852e28d.png)
